// TODO: change to enum type from TypeScript ???

export const APP_INITIALIZE = 'APP_INITIALIZE';

export const APP_SET_BEARER_TOKEN = 'APP_SET_BEARER_TOKEN';
export const APP_SET_DURING_SIGNINGIN = 'APP_SET_DURING_SIGNINGIN';
export const APP_SET_DURING_REGISTRATION = 'APP_SET_DURING_REGISTRATION';

export const APP_SET_PROJECTS_DURING_FETCHING =
  'APP_SET_PROJECTS_DURING_FETCHING';
export const APP_SET_USERS_DURING_FETCHING = 'APP_SET_USERS_DURING_FETCHING';

export const APP_SET_OPENED_PROJECT_ID = 'APP_SET_OPENED_PROJECT_ID';

export const APP_SET_USERS = 'APP_SET_USERS';
export const APP_SET_USER_DATA = 'APP_SET_USER_DATA';
export const APP_SET_PROJECTS = 'APP_SET_PROJECTS';

export const APP_OPEN_APP = 'APP_OPEN_APP';
export const APP_LOGIN = 'APP_LOGIN';
export const APP_REGISTER = 'APP_REGISTER';

export const APP_FETCH_PROJECTS = 'APP_FETCH_PROJECTS';
export const APP_FETCH_USERS = 'APP_FETCH_USERS';

export const APP_OPEN_PROJECT_FROM_SERVER = 'APP_OPEN_PROJECT_FROM_SERVER';
