export const CHANGE_X_DIM = 'CHANGE_X_DIM'; 
export const CHANGE_Y_DIM = 'CHANGE_Y_DIM'; 
export const FETCH_Y_DIM = 'FETCH_Y_DIM'; 

export const FETCH_PROJECT_XML = 'FETCH_PROJECT_XML';
export const CHANGE_PROJECT_XML = 'CHANGE_PROJECT_XML';

export const GRAPH_PROJECT_SET_XML = 'GRAPH_PROJECT_SET_XML';
export const GRAPH_PROJECT_FETCH_XML = 'GRAPH_PROJECT_FETCH_XML';

export const PROJECT_SET_XML = 'PROJECT_SET_XML';
export const PROJECT_SET_ALVIS_PROJECT = 'PROJECT_SET_ALVIS_PROJECT';
export const PROJECT_ADD_AGENT = 'PROJECT_ADD_AGENT';
export const PROJECT_DELETE_AGENT = 'PROJECT_DELETE_AGENT';
export const PROJECT_MODIFY_AGENT = 'PROJECT_MODIFY_AGENT';