export const APP_SET_BEARER_TOKEN = 'APP_SET_BEARER_TOKEN'; 
export const APP_SET_DURING_SIGNINGIN = 'APP_SET_DURING_SIGNINGIN'; 
export const APP_SET_DURING_REGISTRATION = 'APP_SET_DURING_REGISTRATION'; 

export const APP_OPEN_APP = 'APP_OPEN_APP'; 
export const APP_LOGIN = 'APP_LOGIN'; 
export const APP_REGISTER = 'APP_REGISTER';