export const PROJECT_SET_XML = 'PROJECT_SET_XML';
export const PROJECT_SET_ALVIS_PROJECT = 'PROJECT_SET_ALVIS_PROJECT';

export const PROJECT_ADD_PAGE = 'PROJECT_ADD_PAGE';
export const PROJECT_DELETE_PAGE = 'PROJECT_DELETE_PAGE';
export const PROJECT_MODIFY_PAGE = 'PROJECT_MODIFY_PAGE';

export const PROJECT_ADD_AGENT = 'PROJECT_ADD_AGENT';
export const PROJECT_DELETE_AGENT = 'PROJECT_DELETE_AGENT';
export const PROJECT_MODIFY_AGENT = 'PROJECT_MODIFY_AGENT';

export const PROJECT_ADD_PORT = 'PROJECT_ADD_PORT';
export const PROJECT_DELETE_PORT = 'PROJECT_DELETE_PORT';
export const PROJECT_MODIFY_PORT = 'PROJECT_MODIFY_PORT';

export const PROJECT_ADD_CONNECTION = 'PROJECT_ADD_CONNECTION';
export const PROJECT_DELETE_CONNECTION = 'PROJECT_DELETE_CONNECTION';
export const PROJECT_MODIFY_CONNECTION = 'PROJECT_MODIFY_CONNECTION';
